from dataclasses import dataclass
from enum import Enum
from datetime import datetime
from typing import List, Dict, Optional, Any
import pandas as pd

class SignalSide(Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    NEUTRAL = "NEUTRAL"

class TradeSide(Enum):
    LONG = "LONG"
    SHORT = "SHORT"

@dataclass
class Signal:
    """Represents a trading signal generated by the strategy."""
    timestamp: datetime
    symbol: str
    side: SignalSide
    strength: float = 0.0

@dataclass
class Trade:
    """Represents an executed trade."""
    timestamp: datetime
    symbol: str
    side: TradeSide
    price: float
    quantity: float
    cost: float = 0.0

@dataclass
class BacktestResult:
    """Container for backtest results."""
    equity_curve: pd.Series
    trades: List[Trade]
    metrics: Dict[str, float]
    config: Dict

class Predictor:
    """Base interface for price predictors."""
    def predict(self, df: pd.DataFrame) -> pd.Series:
        raise NotImplementedError

class MockPredictor(Predictor):
    """Simple mock predictor for testing."""
    def predict(self, df: pd.DataFrame) -> pd.Series:
        # Mock logic: +1% from current close
        if 'close' not in df.columns:
            return pd.Series(dtype=float)
        return df['close'] * 1.01

class Strategy:
    """
    Generates trading signals based on model predictions.
    Can optionally own a Predictor to run inference before signal generation.
    """
    def __init__(self, threshold: float = 0.005, predictor: Optional[Any] = None):
        self.threshold = threshold
        self.predictor = predictor

    def generate_signals(self, df: pd.DataFrame) -> List[Signal]:
        """
        Generates a list of Signals.
        If a predictor is set, it runs prediction first and adds/overwrites 'prediction' column.
        Otherwise, expects 'prediction' column to be present.
        """
        working_df = df.copy()
        
        # Run prediction if predictor available
        if self.predictor:
            try:
                # KronosModel returns a Series with index as timestamps
                # MockPredictor checks full df.
                # We need to handle how predictions align with df.
                # Assuming predictor returns a Series aligned with `df` (historical) OR future.
                # For `KronosModel` (Real), it predicts *future*.
                # For basic Mock, it's element-wise.
                
                # If we are backtesting, we usually want element-wise "what would the model have predicted at T?"
                # KronosModel.predict(df) currently takes LAST lookback and returns NEXT 1.
                # This doesn't support vectorised backtesting easily unless we loop.
                # However, MockPredictor is vectorised.
                
                # For now, let's assume we handle the series as is.
                preds = self.predictor.predict(working_df)
                
                # If scalar or single row (Real Model)
                if len(preds) == 1:
                     # Live inference scenario: Compare LAST price to FUTURE prediction
                     future_ts = preds.index[0]
                     pred_price = preds.iloc[0]
                     last_close = working_df['close'].iloc[-1]
                     
                     upper = last_close * (1 + self.threshold)
                     lower = last_close * (1 - self.threshold)
                     
                     side = SignalSide.NEUTRAL
                     strength = 0.0
                     
                     if pred_price > upper:
                         side = SignalSide.LONG
                         strength = (pred_price - upper) / last_close
                     elif pred_price < lower:
                         side = SignalSide.SHORT
                         strength = (lower - pred_price) / last_close
                         
                     # Generate single signal
                     return [Signal(
                         timestamp=future_ts,
                         symbol="BTC-USD", # TODO: pass symbol in kwargs or infer
                         side=side,
                         strength=strength
                     )]
                else:
                    # element wise (Mock or Backtest)
                    working_df['prediction'] = preds
                    
            except Exception as e:
                print(f"Prediction error: {e}")
                pass

        if 'prediction' not in working_df.columns:
            # Fallback if no predictor or failed, check columns
             if 'prediction' not in df.columns:
                 raise ValueError("DataFrame must contain 'prediction' column or Strategy must have a generic predictor.")

        signals = []
        for timestamp, row in working_df.iterrows():
            price = row['close']
            
            # Handle prediction
            if 'prediction' in row:
                pred = row['prediction']
            else:
                continue

            # Skip if any value is NaN
            if pd.isna(price) or pd.isna(pred):
                continue
                
            upper_bound = price * (1 + self.threshold)
            lower_bound = price * (1 - self.threshold)
            
            side = SignalSide.NEUTRAL
            strength = 0.0
            
            if pred > upper_bound:
                side = SignalSide.LONG
                strength = (pred - upper_bound) / price
            elif pred < lower_bound:
                side = SignalSide.SHORT
                strength = (lower_bound - pred) / price
            
            # Only create signal if not NEUTRAL (optimization)
            # But legacy code appended all, let's keep consistent? 
            # Original code appended all even neutral.
            signal = Signal(
                timestamp=timestamp, # type: ignore
                symbol="BTC-USD", 
                side=side,
                strength=strength
            )
            signals.append(signal)
            
        return signals
