from dataclasses import dataclass
from enum import Enum
from datetime import datetime
from typing import List, Dict, Optional
import pandas as pd

class SignalSide(Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    NEUTRAL = "NEUTRAL"

class TradeSide(Enum):
    LONG = "LONG"
    SHORT = "SHORT"

@dataclass
class Signal:
    """Represents a trading signal generated by the strategy."""
    timestamp: datetime
    symbol: str
    side: SignalSide
    strength: float = 0.0

@dataclass
class Trade:
    """Represents an executed trade."""
    timestamp: datetime
    symbol: str
    side: TradeSide
    price: float
    quantity: float
    cost: float = 0.0

@dataclass
class BacktestResult:
    """Container for backtest results."""
    equity_curve: pd.Series
    trades: List[Trade]
    metrics: Dict[str, float]
    config: Dict

class Strategy:
    """
    Generates trading signals based on model predictions.
    Logic:
      - LONG if prediction > current_price * (1 + threshold)
      - SHORT if prediction < current_price * (1 - threshold)
      - NEUTRAL otherwise
    """
    def __init__(self, threshold: float = 0.005):
        self.threshold = threshold

    def generate_signals(self, df: pd.DataFrame) -> List[Signal]:
        """
        Generates a list of Signals from a DataFrame containing 'close' and 'prediction' columns.
        """
        signals = []
        if 'prediction' not in df.columns or 'close' not in df.columns:
            raise ValueError("DataFrame must contain 'prediction' and 'close' columns")

        for timestamp, row in df.iterrows():
            price = row['close']
            pred = row['prediction']
            
            # Skip if any value is NaN
            if pd.isna(price) or pd.isna(pred):
                continue
                
            upper_bound = price * (1 + self.threshold)
            lower_bound = price * (1 - self.threshold)
            
            side = SignalSide.NEUTRAL
            strength = 0.0
            
            if pred > upper_bound:
                side = SignalSide.LONG
                strength = (pred - upper_bound) / price
            elif pred < lower_bound:
                side = SignalSide.SHORT
                strength = (lower_bound - pred) / price
            
            signal = Signal(
                timestamp=timestamp, # type: ignore
                symbol="BTC-USD", # TODO: Pass symbol as arg or infer
                side=side,
                strength=strength
            )
            signals.append(signal)
            
        return signals
